# backend/database.py
# ============================================================
# Database connection using SQLAlchemy (sync for simplicity).
# Tables are auto-created on startup via create_all().
# In production you'd use Alembic migrations instead.
# ============================================================

from sqlalchemy import create_engine, Column, String, Float, Integer, DateTime, Text, Boolean
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker
from datetime import datetime

from backend.config import get_settings

settings = get_settings()

# Create the SQLAlchemy engine
engine = create_engine(
    settings.database_url,
    pool_pre_ping=True,   # reconnect if connection dropped
    pool_size=5,
    max_overflow=10,
)

SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
Base = declarative_base()


# ============================================================
# Database Models (ORM)
# ============================================================

class Teacher(Base):
    """A teacher who uses the dashboard."""
    __tablename__ = "teachers"

    id = Column(String, primary_key=True)           # e.g. "TCH_001"
    name = Column(String, nullable=False)
    email = Column(String, unique=True, nullable=False)
    hashed_password = Column(String, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow)


class Student(Base):
    """A student who is tracked during class."""
    __tablename__ = "students"

    id = Column(String, primary_key=True)           # e.g. "STU_001"
    name = Column(String, nullable=False)
    grade_level = Column(Integer, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow)


class ClassSession(Base):
    """A single class session (one period of teaching)."""
    __tablename__ = "class_sessions"

    id = Column(String, primary_key=True)           # e.g. "CLASS_001"
    teacher_id = Column(String, nullable=False)
    subject = Column(String, nullable=False)
    started_at = Column(DateTime, default=datetime.utcnow)
    ended_at = Column(DateTime, nullable=True)
    is_active = Column(Boolean, default=True)


class ActivityRecord(Base):
    """One data point from a student during a class session."""
    __tablename__ = "activity_records"

    id = Column(Integer, primary_key=True, autoincrement=True)
    session_id = Column(String, nullable=False)
    student_id = Column(String, nullable=False)
    timestamp = Column(DateTime, default=datetime.utcnow)

    # Raw BYOD metrics (what the student tracker sends)
    app_switches = Column(Integer, default=0)
    keystroke_intensity = Column(Integer, default=0)
    poll_participation = Column(Integer, default=0)
    quiz_score = Column(Float, nullable=True)
    collaboration_actions = Column(Integer, default=0)
    inactivity_periods = Column(Integer, default=0)
    activity_type = Column(String, default="lecture")
    subject = Column(String, default="unknown")
    hour = Column(Integer, default=9)

    # ML output (what the backend computes)
    baseline_engagement = Column(Float, nullable=True)
    current_engagement = Column(Float, nullable=True)
    anomaly_score = Column(Float, nullable=True)


class Alert(Base):
    """An intervention suggestion generated by the ML pipeline."""
    __tablename__ = "alerts"

    id = Column(Integer, primary_key=True, autoincrement=True)
    session_id = Column(String, nullable=False)
    student_id = Column(String, nullable=False)
    timestamp = Column(DateTime, default=datetime.utcnow)
    suggestion_text = Column(Text, nullable=False)
    suggestion_type = Column(String, nullable=False)
    severity = Column(String, nullable=False)       # "medium" | "high"
    anomaly_score = Column(Float, nullable=False)
    dismissed = Column(Boolean, default=False)


# ============================================================
# Helpers
# ============================================================

def create_tables():
    """Create all tables if they don't exist (safe to call multiple times)."""
    Base.metadata.create_all(bind=engine)


def get_db():
    """FastAPI dependency that yields a DB session and closes it after."""
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()


class TeacherFeedback(Base):
    """
    Teacher confirms or rejects an alert suggestion.
    This is our training signal — over time we use this to retrain.
    """
    __tablename__ = "teacher_feedback"

    id = Column(Integer, primary_key=True, autoincrement=True)
    alert_id = Column(Integer, nullable=False)
    session_id = Column(String, nullable=False)
    student_id = Column(String, nullable=False)
    timestamp = Column(DateTime, default=datetime.utcnow)
    action = Column(String, nullable=False)   # "helpful" | "not_helpful" | "acted_on"
    note = Column(Text, nullable=True)        # optional teacher comment
    actual_engagement_improved = Column(Boolean, nullable=True)  # follow-up observation
